// diagram/src/App.tsx
import React, { useRef, useState } from 'react';
import logo from './logo.svg';
import './App.css';
import { BrowserRouter, Routes, Route } from 'react-router-dom';

import Home from './Componenets/home';
import Menu from './Componenets/contextMenu';

function App() {
  
  return (
    <div>
       
      <BrowserRouter>
          <Routes>
              <Route path="/" element={<Home />} />
        </Routes>
      </BrowserRouter>
    </div>
  );
}

export default App;

// diagram/src/App.svelte
<script lang="ts">
import { Router, Link, Route } from "svelte-routing";
import Diagram from "./routes/diagram.svelte";
import Home from "./routes/home.svelte";
import Menu from "./routes/menu.svelte";
let isSubmitted = false;
</script>
<div>
	<Menu />
	<Router>
		<Route path="/diagram" component={Diagram} />
		<Route path="/">
	<Home />
		</Route>
	</Router>
</div>
